### ISSUE TITLE
Главная страница. Текстовый блок "Воспользуйтесь современными возможностями..." наезжает на изображение

### ISSUE THREAD

**Issue by Slaviksssss** [netology-code/bjs-2-homeworks#108]
## Описание проблемы

**Шаги по воспроизведению**

1. Открыть главную страницу веб-сайта NeuroStartUp в мобильном браузере Chrome

2. Пролистать страницу до блока "Воспользуйтесь современными возможностями..."

**Ожидаемый результат**

Текст не наезжает на изображение

**Фактический результат**

Текст наезжает на изображение (см. скриншот)

**Программное окружение**

- Устройство: iPhone 8+ (iOS 12.1)

- Браузер: Chrome (70.0.3538.75)

**Скриншоты**

![68747470733a2f2f692e696d6775722e636f6d2f484a3156624d6a2e706e67](https://github.com/user-attachments/assets/59dab802-3338-4037-9963-7102c38f6cb1)

@solarrust

**Comment by vovachebr** [comment]
К данному репозиторию это не имеет никакого отношения
