### ISSUE TITLE
Активация строго режима в задаче 1

### ISSUE THREAD

**Issue by smileperez** [netology-code/bjs-2-homeworks#16]
В задаче 1-1 и 1-2 по заданию требуется активация "Строгого режима", но ранее про строгий режим нигде не упоминалось (ни в отладочном ролике, ни в первой лекции).
Поэтому данное действие ставит в ступор студентов.  Неопытным новичкам даже сложно сходу понять к чему это относится, чтобы правильно загуглить.

Как подсказывают коллеги, первое упоминание строго режима есть только во второй лекции.

Будет прекрасно, если добавите краткое объяснение действия в описание задачи.
Спасибо.

**Comment by vovachebr** [comment]
Добавлено
