### ISSUE TITLE
Ошибка в задании/тесте

### ISSUE THREAD

**Issue by kalynov-alar** [netology-code/bjs-2-homeworks#31]
задача 1, задание 6.
![image](https://user-images.githubusercontent.com/91879501/180614887-5375f080-eef1-4264-8573-1da6a856931e.png)

по тексту задания следует к параметрам родительского конструктора добавить еще один параметр (то есть в конец).
однако при тестировании появляются ошибки связанные с тем что в тесте новый параметр (autor) передается первым
https://github.com/netology-code/bjs-2-homeworks/blob/96d2f342c7d874ede133db8f9b5e11b098a7767d/5.classes/tests.js#L50
https://github.com/netology-code/bjs-2-homeworks/blob/96d2f342c7d874ede133db8f9b5e11b098a7767d/5.classes/tests.js#L59
https://github.com/netology-code/bjs-2-homeworks/blob/96d2f342c7d874ede133db8f9b5e11b098a7767d/5.classes/tests.js#L65
https://github.com/netology-code/bjs-2-homeworks/blob/96d2f342c7d874ede133db8f9b5e11b098a7767d/5.classes/tests.js#L71

**Comment by vovachebr** [comment]
Добрый день. _Добавить еще один параметр (то есть в конец)._ Не обязательно в конец. Порядок аргументов у потомка может не соответствовать порядку аргументов у родительского класса.
