### ISSUE TITLE
Опечатка в описании задания к лекции 1 «Основные понятия».

### ISSUE THREAD

**Issue by PavlyukovVladimir** [netology-code/bjs-2-homeworks#42]
Опечатка, напечатано "готовой ставки", а должно быть "годовой ставки". [ссылка](https://github.com/netology-code/bjs-2-homeworks/tree/bjs-53/1.base-concepts#:~:text=1%20%D0%B8%20%D0%B8%D0%B7-,%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BE%D0%B9%20%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8,-%E2%80%94%20%D0%B2%20%D0%BC%D0%B5%D1%81%D1%8F%D1%87%D0%BD%D1%83%D1%8E.)

**Comment by vovachebr** [comment]
Исправлено
