### ISSUE TITLE
Опечатка в тесте 3го задания

### ISSUE THREAD

**Issue by darkdram** [netology-code/bjs-2-homeworks#5]
#### Ожидаемый результат

`it("[0,1,2] === [0, 1] false", () => {
       expect(compareArrays([0,1,2], [0, 1])).toEqual(false)
})`

#### Фактический результат

https://github.com/netology-code/bjs-2-homeworks/blob/f0001d1503b1a2f447aa725f999bdfb12e9b838c/3.arrays/tests.js#L15-L17

**Comment by copperfox777** [comment]
Исправлено!
