### ISSUE TITLE
ошибка в описании задания к первой задаче

### ISSUE THREAD

**Issue by Uldez89** [netology-code/bjs-2-homeworks#66]
min =  Infinity, 
max = -Infinity.
возможно наоборот

**Comment by vovachebr** [comment]
Всё верно. `min = Infinity,` присваивается, чтобы на первой же итерации значение переприсвоить на иное....Если присвоение будет `min = -Infinity,`, то никакое значение из массива не будет меньше минус бесконечности....Аналогично и с переменной `max` .
